name: Run Test, Quality and Release
on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/CHANGELOG.md'
permissions:
  contents: write
  pull-requests: write
env:
  PORT: 3000
  NAME_AND_PORT_SERVICES_LIST: users:4001,products:4002,tasks:4003

jobs:
  testJest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        node-version: [ 16, 18, 20 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Run EsLint quality check
        run: npm run eslint

  sonarCloudCheck:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: testJest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install

      - name: Test and coverage
        run: npm run coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release-please:
    runs-on: ubuntu-latest
    needs: testJest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          release-type: simple

  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: testJest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wms-gateway:latest